//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Localization.Shell
{
    public static class Window
    {
        public static readonly string Title = "Localization.Shell.Window.Title";
        public static readonly string Subtitle = "Localization.Shell.Window.Subtitle";
    }

    public static class Search
    {
        public static readonly string Placeholder = "Localization.Shell.Search.Placeholder";
    }

    public static class Actions
    {
        public static readonly string Local = "Localization.Shell.Actions.Local";
        public static readonly string Settings = "Localization.Shell.Actions.Settings";
    }

    public static class Controls
    {
        public static readonly string Minimize = "Localization.Shell.Controls.Minimize";
        public static readonly string Maximize = "Localization.Shell.Controls.Maximize";
        public static readonly string Restore = "Localization.Shell.Controls.Restore";
        public static readonly string Close = "Localization.Shell.Controls.Close";
    }

}
namespace Localization.Main
{
    public static class Categories
    {
        public static readonly string All = "Localization.Main.Categories.All";
        public static readonly string Cartoon = "Localization.Main.Categories.Cartoon";
        public static readonly string Starry = "Localization.Main.Categories.Starry";
        public static readonly string Illustration = "Localization.Main.Categories.Illustration";
        public static readonly string Dynamic = "Localization.Main.Categories.Dynamic";
        public static readonly string Local = "Localization.Main.Categories.Local";
    }

    public static class Section
    {
        public static readonly string All = "Localization.Main.Section.All";
        public static readonly string Cartoon = "Localization.Main.Section.Cartoon";
        public static readonly string Starry = "Localization.Main.Section.Starry";
        public static readonly string Illustration = "Localization.Main.Section.Illustration";
        public static readonly string Dynamic = "Localization.Main.Section.Dynamic";
        public static readonly string Local = "Localization.Main.Section.Local";
    }

    public static class Labels
    {
        public static readonly string Count = "Localization.Main.Labels.Count";
    }

    public static class Card
    {
        public static readonly string Preview = "Localization.Main.Card.Preview";
        public static readonly string SetWallpaper = "Localization.Main.Card.SetWallpaper";
        public static readonly string Dynamic = "Localization.Main.Card.Dynamic";
        public static readonly string Current = "Localization.Main.Card.Current";
        public static readonly string Planned = "Localization.Main.Card.Planned";
    }

    public static class Empty
    {
        public static readonly string Icon = "Localization.Main.Empty.Icon";
        public static readonly string Text = "Localization.Main.Empty.Text";
    }

    public static class Status
    {
        public static readonly string Loading = "Localization.Main.Status.Loading";
        public static readonly string DynamicPlanned = "Localization.Main.Status.DynamicPlanned";
    }

}
namespace Localization.Preview
{
    public static class Labels
    {
        public static readonly string Resolution = "Localization.Preview.Labels.Resolution";
        public static readonly string Apply = "Localization.Preview.Labels.Apply";
        public static readonly string Close = "Localization.Preview.Labels.Close";
    }

}
namespace Localization.Settings
{
    public static class Page
    {
        public static readonly string Title = "Localization.Settings.Page.Title";
        public static readonly string Subtitle = "Localization.Settings.Page.Subtitle";
        public static readonly string Save = "Localization.Settings.Page.Save";
    }

    public static class AutoStart
    {
        public static readonly string Title = "Localization.Settings.AutoStart.Title";
        public static readonly string Desc = "Localization.Settings.AutoStart.Desc";
    }

    public static class AutoRotate
    {
        public static readonly string Title = "Localization.Settings.AutoRotate.Title";
        public static readonly string Desc = "Localization.Settings.AutoRotate.Desc";
    }

    public static class BatterySaver
    {
        public static readonly string Title = "Localization.Settings.BatterySaver.Title";
        public static readonly string Desc = "Localization.Settings.BatterySaver.Desc";
    }

    public static class ContentFilter
    {
        public static readonly string Title = "Localization.Settings.ContentFilter.Title";
        public static readonly string Desc = "Localization.Settings.ContentFilter.Desc";
    }

}
namespace Localization.Toast
{
    public static class Messages
    {
        public static readonly string Applied = "Localization.Toast.Messages.Applied";
        public static readonly string Saved = "Localization.Toast.Messages.Saved";
        public static readonly string Minimized = "Localization.Toast.Messages.Minimized";
        public static readonly string Maximized = "Localization.Toast.Messages.Maximized";
        public static readonly string Restored = "Localization.Toast.Messages.Restored";
        public static readonly string Closed = "Localization.Toast.Messages.Closed";
        public static readonly string Reopened = "Localization.Toast.Messages.Reopened";
        public static readonly string LocalImported = "Localization.Toast.Messages.LocalImported";
        public static readonly string AutoRotated = "Localization.Toast.Messages.AutoRotated";
    }

}
